# Generated by Django 4.0.5 on 2022-06-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('Dyslexia Assesment', 'Dyslexia Assesment'), ('Intervention Class', 'Intervention Class')], help_text='What type of session would you like book?', max_length=20)),
                ('booking_date', models.DateTimeField()),
                ('time_slot', models.CharField(choices=[('17:00', '17:00'), ('18:00', '18:00'), ('18:00', '18:00'), ('18:00', '18:00')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
    ]
