# Generated by Django 4.0.5 on 2022-06-28 08:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('Dyslexia Assesment', 'Dyslexia Assesment'), ('Intervention Class', 'Intervention Class')], default='', help_text='What type of session would you like book?', max_length=20)),
                ('booking_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Virtual', 'Virtual')], max_length=20)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date', '-time_slot'],
                'unique_together': {('booking_date', 'time_slot')},
            },
        ),
    ]
