# Generated by Django 4.0.5 on 2022-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Virtual', 'Virtual')], max_length=20),
        ),
    ]
