# Generated by Django 4.0.5 on 2022-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_type',
            field=models.CharField(choices=[('Dyslexia Assesment', 'Dyslexia Assesment'), ('Intervention Class', 'Intervention Class')], default='', help_text='What type of session would you like book?', max_length=20),
        ),
    ]
