# Generated by Django 4.0.5 on 2022-06-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_class_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-time_slot']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'time_slot')},
        ),
    ]
