# Generated by Django 4.0.5 on 2022-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_type',
            field=models.CharField(choices=[('Dyslexia Assesment', 'Dyslexia Assesment'), ('Intervention Class', 'Intervention Class')], default='', max_length=20),
        ),
    ]
