# Generated by Django 4.0.5 on 2022-08-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_options_booking_unique_time_slot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_time_slot',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'time_slot')},
        ),
    ]
