# Generated by Django 4.0.5 on 2022-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_unique_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('booking_date', 'time_slot'), name='unique_time_slot'),
        ),
    ]
