# Generated by Django 4.0.5 on 2022-06-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_client_first_name_client_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
